"""Describes render commands generated by Clay."""

import ctypes
from dataclasses import dataclass
from typing import Any

from pyclay._clay import _types as ct
from pyclay._clay._enums import Clay_RenderCommandType
from pyclay.configs import BorderWidth, Color, CornerRadius
from pyclay.data import BoundingBox


@dataclass(frozen=True)
class TextRenderData:
    """Command generated by Clay when the type is TEXT."""

    string_contents: str
    text_color: Color
    font_id: int
    font_size: int
    letter_spacing: int
    line_height: int

    @classmethod
    def from_ctypes(cls, c: ct.Clay_TextRenderData) -> TextRenderData:
        """Convert the underlying ctypes structure to the Python dataclass."""
        raw_str: bytes = (
            ctypes.string_at(
                c.stringContents.chars,
                c.stringContents.length,
            )
            if c.stringContents.chars
            else b""
        )
        text: str = raw_str.decode("utf-8", errors="replace")

        return cls(
            string_contents=text,
            text_color=Color.from_ctypes(c.textColor),
            font_id=c.fontId,
            font_size=c.fontSize,
            letter_spacing=c.letterSpacing,
            line_height=c.lineHeight,
        )


@dataclass(frozen=True)
class RectangleRenderData:
    """Command generated by Clay when the type is RECTANGLE."""

    background_color: Color
    corner_radius: CornerRadius

    @classmethod
    def from_ctypes(cls, c: ct.Clay_RectangleRenderData) -> RectangleRenderData:
        """Convert the underlying ctypes structure to the Python dataclass."""
        return cls(
            background_color=Color.from_ctypes(c.backgroundColor),
            corner_radius=CornerRadius.from_ctypes(c.cornerRadius),
        )


@dataclass(frozen=True)
class ImageRenderData:
    """Command generated by Clay when the type is IMAGE."""

    background_color: Color
    corner_radius: CornerRadius
    image_data: Any = None

    @classmethod
    def from_ctypes(cls, c: ct.Clay_ImageRenderData) -> ImageRenderData:
        """Convert the underlying ctypes structure to the Python dataclass."""
        return cls(
            background_color=Color.from_ctypes(c.backgroundColor),
            corner_radius=CornerRadius.from_ctypes(c.cornerRadius),
            # TODO(oxygen): load user data
            image_data=c.imageData,
        )


@dataclass(frozen=True)
class CustomRenderData:
    """Command generated by Clay when the type is CUSTOM."""

    background_color: Color
    corner_radius: CornerRadius
    custom_data: Any = None

    @classmethod
    def from_ctypes(cls, c: ct.Clay_CustomRenderData) -> CustomRenderData:
        """Convert the underlying ctypes structure to the Python dataclass."""
        return cls(
            background_color=Color.from_ctypes(c.backgroundColor),
            corner_radius=CornerRadius.from_ctypes(c.cornerRadius),
            # TODO(oxygen): load user data
            custom_data=c.customData,
        )


@dataclass(frozen=True)
class ClipRenderData:
    """Command generated by Clay when the type is SCISSOR_START or SCISSOR_END."""

    horizontal: bool
    vertical: bool

    @classmethod
    def from_ctypes(cls, c: ct.Clay_ClipRenderData) -> ClipRenderData:
        """Convert the underlying ctypes structure to the Python dataclass."""
        return cls(horizontal=c.horizontal, vertical=c.vertical)


@dataclass(frozen=True)
class OverlayColorRenderData:
    """Command generated by Clay when the type is OVERLAY_START or OVERLAY_END."""

    color: Color

    @classmethod
    def from_ctypes(cls, c: ct.Clay_OverlayColorRenderData) -> OverlayColorRenderData:
        """Convert the underlying ctypes structure to the Python dataclass."""
        return cls(color=Color.from_ctypes(c.color))


@dataclass(frozen=True)
class BorderRenderData:
    """Command generated by Clay when the type is BORDER."""

    color: Color
    corner_radius: CornerRadius
    width: BorderWidth

    @classmethod
    def from_ctypes(cls, c: ct.Clay_BorderRenderData) -> BorderRenderData:
        """Convert the underlying ctypes structure to the Python dataclass."""
        return cls(
            color=Color.from_ctypes(c.color),
            corner_radius=CornerRadius.from_ctypes(c.cornerRadius),
            width=BorderWidth.from_ctypes(c.width),
        )


@dataclass(frozen=True)
class RenderCommand:
    """Represents a single render command generated by Clay."""

    bounding_box: BoundingBox
    command_type: Clay_RenderCommandType

    # optional data depending on the type
    rectangle: RectangleRenderData | None = None
    text: TextRenderData | None = None
    image: ImageRenderData | None = None
    custom: CustomRenderData | None = None
    border: BorderRenderData | None = None
    clip: ClipRenderData | None = None
    overlay_color: OverlayColorRenderData | None = None

    user_data: Any = None
    id: int = 0
    z_index: int = 0

    @classmethod
    def from_ctypes(cls, c: ct.Clay_RenderCommand) -> RenderCommand:
        """Convert the underlying ctypes structure to the Python dataclass."""
        cmd_type: Clay_RenderCommandType = Clay_RenderCommandType(c.commandType)
        cmd_types = Clay_RenderCommandType

        rectangle = text = image = custom = border = clip = overlay_color = None
        match cmd_type:
            case cmd_types.CLAY_RENDER_COMMAND_TYPE_RECTANGLE:
                rectangle = RectangleRenderData.from_ctypes(c.renderData.rectangle)
            case cmd_types.CLAY_RENDER_COMMAND_TYPE_TEXT:
                text = TextRenderData.from_ctypes(c.renderData.text)
            case cmd_types.CLAY_RENDER_COMMAND_TYPE_IMAGE:
                image = ImageRenderData.from_ctypes(c.renderData.image)
            case cmd_types.CLAY_RENDER_COMMAND_TYPE_CUSTOM:
                custom = CustomRenderData.from_ctypes(c.renderData.custom)
            case cmd_types.CLAY_RENDER_COMMAND_TYPE_BORDER:
                border = BorderRenderData.from_ctypes(c.renderData.border)
            case (
                cmd_types.CLAY_RENDER_COMMAND_TYPE_SCISSOR_START
                | cmd_types.CLAY_RENDER_COMMAND_TYPE_SCISSOR_END
            ):
                clip = ClipRenderData.from_ctypes(c.renderData.clip)
            case (
                cmd_types.CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_START
                | cmd_types.CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_END
            ):
                overlay_color = OverlayColorRenderData.from_ctypes(
                    c.renderData.overlayColor,
                )
        # TODO(oxygen): load user data
        user_data = None

        return cls(
            bounding_box=BoundingBox.from_ctypes(c.boundingBox),
            command_type=cmd_type,
            rectangle=rectangle,
            text=text,
            image=image,
            custom=custom,
            border=border,
            clip=clip,
            overlay_color=overlay_color,
            user_data=user_data,
            id=c.id,
            z_index=c.zIndex,
        )
